# Tags for yaml import, used by yaml_jinja.py
#
import yaml


class U8Tag(yaml.YAMLObject):
    """u8 tag generated by device tree compiler:
    .e.g.
            local-mac-address: [!u8 [0xb8, 0x27, 0xeb, 0xad, 0xbb, 0x9d]]
    """

    yaml_tag = "!u8"

    def __init__(self):
        pass

    def __repr__(self):
        return "u8"

    @classmethod
    def from_yaml(cls, loader, node):
        # TODO - should this instanciate U8Tag ?
        return bytearray([int(x.value, 0) for x in node.value])

    # TODO  - add to_yaml()
