# -*- Makefile -*-
# ARM GNU Toolchain
# https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads
# Assumes toolchain is in PATH

CXX=c:/LLVM11/bin/clang++
CPPFLAGS=-I../../cxx17_mmio_interface/include/
CXXFLAGS=-target arm-none-eabi -mcpu=cortex-m3 -g -O2 -std=c++17
LDFLAGS=-nostartfiles

all : test_CMSDK_CM3 test_CMSDK_CM3.disasm  test_single_write test_single_write.disasm 

%.disasm : %
	${CROSS_COMPILE}objdump -S $<  > $@
